export const svgConfigsMap = new Map([
  [
    "Sec1",
    new Map([
      [
        "Sector32",
        {
          row_count: 8,
          col_count: 11,
          spacingX: 50,
          spacingY: 100,
          radius: 15,
          rows: [
            new Map([
              [
                ["config", { rowName: "R", align: "right" }],
                [
                  "cols",
                  ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
                ],
              ],
              [
                ["config", { rowName: "S", align: "right" }],
                [
                  "cols",
                  ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
                ],
              ],
              [
                ["config", { rowName: "T", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]],
              ],
              [
                ["config", { rowName: "U", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8", "9"]],
              ],
              [
                ["config", { rowName: "V", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8", "9"]],
              ],
              [
                ["config", { rowName: "W", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "X", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7"]],
              ],
              [
                ["config", { rowName: "Y", align: "center" }],
                ["cols", ["1", "2", "3", "4", "5"]],
              ],
            ]),
          ],
        },
      ],
      [
        "Sector31",
        {
          row_count: 8,
          col_count: 8,
          spacingX: 50,
          spacingY: 100,
          radius: 15,
          rows: [
            new Map([
              [
                ["config", { rowName: "R", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "S", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "T", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "U", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "V", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "W", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "X", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "Y", align: "center" }],
                ["cols", ["1", "2", "3", "4", "5", "6"]],
              ],
            ]),
          ],
        },
      ],
      [
        "Sector30",
        {
          row_count: 8,
          col_count: 8,
          spacingX: 50,
          spacingY: 100,
          radius: 15,
          rows: [
            new Map([
              [
                ["config", { rowName: "R", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "S", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "T", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "U", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "V", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "W", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "X", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8"]],
              ],
              [
                ["config", { rowName: "Y", align: "center" }],
                ["cols", ["1", "2", "3", "4", "5", "6"]],
              ],
            ]),
          ],
        },
      ],
      [
        "Sector29",
        {
          row_count: 8,
          col_count: 12,
          spacingX: 50,
          spacingY: 100,
          radius: 15,
          rows: [
            new Map([
              [
                ["config", { rowName: "R", align: "right" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                  ],
                ],
              ],
              [
                ["config", { rowName: "S", align: "right" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                  ],
                ],
              ],
              [
                ["config", { rowName: "T", align: "right" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                  ],
                ],
              ],
              [
                ["config", { rowName: "U", align: "right" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                  ],
                ],
              ],
              [
                ["config", { rowName: "V", align: "right" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                  ],
                ],
              ],
              [
                ["config", { rowName: "W", align: "right" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                  ],
                ],
              ],
              [
                ["config", { rowName: "X", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8", "9"]],
              ],
              [
                ["config", { rowName: "Y", align: "right" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7"]],
              ],
            ]),
          ],
        },
      ],
      [
        "Sector28",
        {
          row_count: 8,
          col_count: 22,
          spacingX: 50,
          spacingY: 100,
          radius: 15,
          rows: [
            new Map([
              [
                ["config", { rowName: "R", align: "left" }],
                ["cols", ["1", "2", "3", "4", "5", "6"]],
              ],
              [
                ["config", { rowName: "S", align: "left" }],
                ["cols", ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]],
              ],
              [
                ["config", { rowName: "T", align: "left" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                  ],
                ],
              ],
              [
                ["config", { rowName: "U", align: "left" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                  ],
                ],
              ],
              [
                ["config", { rowName: "V", align: "left" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "19",
                    "20",
                  ],
                ],
              ],
              [
                ["config", { rowName: "W", align: "left" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "19",
                    "20",
                    "21",
                    "22",
                  ],
                ],
              ],
              [
                ["config", { rowName: "X", align: "left" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "19",
                    "20",
                    "21",
                  ],
                ],
              ],
              [
                ["config", { rowName: "Y", align: "left" }],
                [
                  "cols",
                  [
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9",
                    "10",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "19",
                    "20",
                  ],
                ],
              ],
            ]),
          ],
        },
      ],
    ]),
  ],
  [
    "Sec13",
    new Map([
      [
        "Sector32",
        {
          row_count: 7,
          col_count: 11,
          spacingX: 50,
          spacingY: 100,
          radius: 15,
          rows: [
            new Map([
              [
                ["config", { rowName: "A", align: "right" }],
                ["cols", ["1", "2", "3", "4"]],
              ],
              [
                ["config", { rowName: "B", align: "right" }],
                ["cols", ["1", "2", "3", "4"]],
              ],
            ]),
          ],
        },
      ],
      [
        "Sector33",
        {
          row_count: 5,
          col_count: 9,
          spacingX: 50,
          spacingY: 100,
          radius: 15,
          rows: [
            new Map([
              [
                ["config", { rowName: "C", align: "left" }],
                ["cols", ["1", "2", "3", "4"]],
              ],
              [
                ["config", { rowName: "D", align: "left" }],
                ["cols", ["1", "2", "3", "4"]],
              ],
            ]),
          ],
        },
      ],
    ]),
  ],
]);
